# Generated by Django 6.1 on 2026-09-05 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('organisation', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('topic', models.CharField(choices=[('w_ct_t1', 'Joining the pilot'), ('w_ct_t2', 'Partnership'), ('w_ct_t3', 'Technical'), ('w_ct_t4', 'Other')], default='w_ct_t4', max_length=16)),
                ('message', models.TextField(max_length=4000)),
                ('status', models.CharField(choices=[('new', 'New'), ('answered', 'Answered'), ('spam', 'Spam')], default='new', max_length=16)),
                ('source_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
