# Generated by Django 6.1 on 2026-08-27 07:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(choices=[('UZS', 'Uzbek sum'), ('USD', 'US dollar'), ('JPY', 'Japanese yen')], default='UZS', max_length=3)),
                ('fx_rate_to_uzs', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('buyer_name', models.CharField(max_length=160)),
                ('buyer_country', models.CharField(max_length=2)),
                ('quantity_g', models.BigIntegerField(default=0)),
                ('incoterm', models.CharField(blank=True, max_length=8)),
                ('payment_terms', models.CharField(choices=[('lc', 'Letter of credit'), ('cad', 'Cash against documents'), ('advance', 'Advance payment'), ('open', 'Open account')], default='lc', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('in_progress', 'In progress'), ('shipped', 'Shipped'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('signed_on', models.DateField(blank=True, null=True)),
                ('ship_by', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-signed_on', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OfftakeContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('quantity_g', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('fulfilling', 'Being fulfilled'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('delivery_from', models.DateField(blank=True, null=True)),
                ('delivery_to', models.DateField(blank=True, null=True)),
                ('signed_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-signed_on', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PriceTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(choices=[('UZS', 'Uzbek sum'), ('USD', 'US dollar'), ('JPY', 'Japanese yen')], default='UZS', max_length=3)),
                ('fx_rate_to_uzs', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('basis', models.CharField(choices=[('per_tonne', 'Per tonne'), ('per_kg', 'Per kilogram'), ('lot_sum', 'Whole lot')], default='per_tonne', max_length=12)),
                ('grade', models.CharField(blank=True, max_length=8)),
                ('note', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'ordering': ['grade'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('mode', models.CharField(choices=[('reefer', 'Reefer truck'), ('dry_truck', 'Dry truck'), ('rail', 'Rail'), ('air', 'Air')], default='reefer', max_length=12)),
                ('vehicle', models.CharField(blank=True, max_length=64)),
                ('set_point_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('origin', models.CharField(blank=True, max_length=120)),
                ('destination', models.CharField(blank=True, max_length=120)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('departs_at', models.DateTimeField(blank=True, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('loading', 'Loading'), ('in_transit', 'In transit'), ('at_border', 'At the border'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='planned', max_length=12)),
            ],
            options={
                'ordering': ['-departs_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_g', models.BigIntegerField()),
            ],
            options={
                'ordering': ['shipment__code', 'lot__code'],
            },
        ),
    ]
