# Generated by Django 6.1 on 2026-08-27 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        ('lots', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportcontract',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_contracts', to='registry.product'),
        ),
        migrations.AddField(
            model_name='exportcontract',
            name='seller_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_contracts', to='registry.party'),
        ),
        migrations.AddField(
            model_name='offtakecontract',
            name='buyer_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offtake_purchases', to='registry.party'),
        ),
        migrations.AddField(
            model_name='offtakecontract',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offtake_contracts', to='registry.product'),
        ),
        migrations.AddField(
            model_name='offtakecontract',
            name='seller_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offtake_sales', to='registry.party'),
        ),
        migrations.AddField(
            model_name='priceterm',
            name='export_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_terms', to='commercial.exportcontract'),
        ),
        migrations.AddField(
            model_name='priceterm',
            name='offtake_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_terms', to='commercial.offtakecontract'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='carrier_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='registry.party'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='export_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='commercial.exportcontract'),
        ),
        migrations.AddField(
            model_name='shipmentline',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='lots.lot'),
        ),
        migrations.AddField(
            model_name='shipmentline',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='commercial.shipment'),
        ),
        migrations.AddConstraint(
            model_name='shipmentline',
            constraint=models.UniqueConstraint(fields=('shipment', 'lot'), name='uniq_lot_per_shipment'),
        ),
    ]
