# Generated by Django 6.1 on 2026-08-27 07:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PilotTrial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('facility_code', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='planned', max_length=12)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('schedule_days', models.JSONField(default=list)),
                ('protocol', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_on', 'code'],
            },
        ),
        migrations.CreateModel(
            name='QcRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('intake', 'At intake'), ('pre_storage', 'Before storage'), ('in_storage', 'In storage'), ('pre_dispatch', 'Before dispatch'), ('arrival', 'On arrival')], max_length=16)),
                ('inspected_on', models.DateField()),
                ('inspector_label', models.CharField(blank=True, max_length=120)),
                ('measurements', models.JSONField(blank=True, default=dict)),
                ('grade_assigned', models.CharField(blank=True, max_length=8)),
                ('defect_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('lab_document_code', models.CharField(blank=True, max_length=48)),
            ],
            options={
                'ordering': ['lot__code', 'inspected_on'],
            },
        ),
        migrations.CreateModel(
            name='TrialArm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('zeroco', 'ZEROCO'), ('control', 'Control')], max_length=8)),
                ('zone_code', models.CharField(blank=True, max_length=32)),
                ('quantity_g', models.BigIntegerField(default=0)),
                ('projection', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['trial__code', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='TrialObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_index', models.PositiveSmallIntegerField()),
                ('observed_on', models.DateField()),
                ('weight_loss_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('waste_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('firmness_n', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('colour_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('markdown_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('photo_refs', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['arm__trial__code', 'day_index', 'arm__kind'],
            },
        ),
    ]
