# Generated by Django 6.1 on 2026-08-27 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0002_initial'),
        ('quality', '0001_initial'),
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pilottrial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trials', to='registry.product'),
        ),
        migrations.AddField(
            model_name='qcrecord',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qcrecord',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_records', to='lots.lot'),
        ),
        migrations.AddField(
            model_name='trialarm',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_arms', to='lots.lot'),
        ),
        migrations.AddField(
            model_name='trialarm',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arms', to='quality.pilottrial'),
        ),
        migrations.AddField(
            model_name='trialobservation',
            name='arm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='quality.trialarm'),
        ),
        migrations.AddField(
            model_name='trialobservation',
            name='observer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trial_observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='qcrecord',
            index=models.Index(fields=['lot', 'stage'], name='quality_qcr_lot_id_991a87_idx'),
        ),
        migrations.AddConstraint(
            model_name='trialarm',
            constraint=models.UniqueConstraint(fields=('trial', 'kind'), name='uniq_arm_per_trial'),
        ),
        migrations.AddConstraint(
            model_name='trialobservation',
            constraint=models.UniqueConstraint(fields=('arm', 'day_index'), name='uniq_observation_per_day'),
        ),
    ]
