# Generated by Django 6.1 on 2026-08-27 07:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('crit', 'Critical'), ('warn', 'Warning'), ('info', 'Info'), ('good', 'Good')], default='info', max_length=8)),
                ('message_key', models.CharField(max_length=48)),
                ('subject', models.CharField(blank=True, max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
