# Generated by Django 6.1 on 2026-08-27 07:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('actor_label', models.CharField(blank=True, max_length=120)),
                ('action_key', models.CharField(max_length=32)),
                ('object_ref', models.CharField(blank=True, max_length=120)),
                ('capability', models.CharField(blank=True, max_length=32)),
                ('context', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'audit entries',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='DataGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grantee_label', models.CharField(blank=True, max_length=160)),
                ('scope_key', models.CharField(max_length=32)),
                ('fields_key', models.CharField(max_length=32)),
                ('basis', models.CharField(choices=[('owner', 'Owner consent'), ('law', 'Statutory'), ('contract', 'Contractual')], default='owner', max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=12)),
                ('granted_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['grantee_label', 'scope_key'],
            },
        ),
    ]
