# Generated by Django 6.1 on 2026-08-27 07:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('net_weight_g', models.BigIntegerField()),
                ('gross_weight_g', models.BigIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('graded', 'Graded'), ('stored', 'Stored'), ('reserved', 'Reserved'), ('dispatched', 'Dispatched'), ('settled', 'Settled'), ('rejected', 'Rejected'), ('written_off', 'Written off')], db_index=True, default='registered', max_length=16)),
                ('storage_mode', models.CharField(choices=[('zeroco', 'ZEROCO'), ('cold', 'Conventional cold'), ('pre', 'Pre-cool'), ('dry', 'Dry'), ('none', 'Not stored')], default='none', max_length=8)),
                ('harvested_on', models.DateField(blank=True, null=True)),
                ('sell_by', models.DateField(blank=True, null=True)),
                ('trial_arm', models.CharField(blank=True, choices=[('zeroco', 'ZEROCO arm'), ('control', 'Control arm')], default='', max_length=8)),
                ('valuation_minor', models.BigIntegerField(default=0)),
                ('valuation_currency', models.CharField(choices=[('UZS', 'Uzbek sum'), ('USD', 'US dollar'), ('JPY', 'Japanese yen')], default='UZS', max_length=3)),
            ],
            options={
                'ordering': ['-created_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LotEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('actor_label', models.CharField(blank=True, max_length=120)),
                ('facility_code', models.CharField(blank=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(blank=True, choices=[('accept', 'Accepted'), ('warn', 'Warning')], default='', max_length=8)),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['lot__code', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='LotRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('split', 'Split'), ('merge', 'Merge'), ('repack', 'Repack'), ('sample', 'Sample drawn')], max_length=8)),
                ('quantity_g', models.BigIntegerField()),
            ],
            options={
                'ordering': ['parent__code', 'child__code'],
            },
        ),
    ]
