# Generated by Django 6.1 on 2026-08-27 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='origin_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='registry.farm'),
        ),
        migrations.AddField(
            model_name='lot',
            name='owner_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='registry.party'),
        ),
        migrations.AddField(
            model_name='lot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='registry.product'),
        ),
        migrations.AddField(
            model_name='lotevent',
            name='actor_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lot_events', to='registry.party'),
        ),
        migrations.AddField(
            model_name='lotevent',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lot_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotevent',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='lots.lot'),
        ),
        migrations.AddField(
            model_name='lotrelation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parents', to='lots.lot'),
        ),
        migrations.AddField(
            model_name='lotrelation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='lots.lot'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['status', 'sell_by'], name='lots_lot_status_ad0d69_idx'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['owner_party', 'status'], name='lots_lot_owner_p_331f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='lotevent',
            index=models.Index(fields=['lot', 'occurred_at'], name='lots_loteve_lot_id_7cb762_idx'),
        ),
        migrations.AddConstraint(
            model_name='lotevent',
            constraint=models.UniqueConstraint(fields=('lot', 'sequence'), name='uniq_lot_event_sequence'),
        ),
        migrations.AddConstraint(
            model_name='lotrelation',
            constraint=models.UniqueConstraint(fields=('parent', 'child', 'kind'), name='uniq_lot_relation'),
        ),
        migrations.AddConstraint(
            model_name='lotrelation',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('child')), _negated=True), name='lot_relation_not_self'),
        ),
    ]
