# Generated by Django 6.1 on 2026-08-27 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='custody_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots_in_custody', to='registry.party'),
        ),
    ]
