# Generated by Django 6.1 on 2026-08-27 07:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('label_key', models.CharField(max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'capabilities',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('label_key', models.CharField(max_length=32)),
                ('icon', models.CharField(max_length=32)),
                ('required_checks', models.JSONField(default=list)),
                ('licence_register', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name_uz', models.CharField(max_length=64)),
                ('name_ru', models.CharField(max_length=64)),
                ('name_en', models.CharField(max_length=64)),
                ('variety', models.CharField(blank=True, max_length=64)),
                ('hs_code', models.CharField(blank=True, max_length=16)),
                ('qc_spec', models.JSONField(blank=True, default=dict)),
                ('shelf_life_days', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('label_key', models.CharField(max_length=32)),
                ('register', models.CharField(blank=True, max_length=64)),
                ('mode', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=8)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('pinfl', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='pending', max_length=16)),
                ('oneid_verified', models.BooleanField(default=False)),
                ('eimzo_verified', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['display_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('tin', models.CharField(blank=True, max_length=24)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('district', models.CharField(blank=True, max_length=64)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('review', 'In review'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('verified_on', models.DateField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=120)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='registry.organisationtype')),
            ],
            options={
                'verbose_name_plural': 'parties',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('owner_name', models.CharField(blank=True, max_length=160)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('district', models.CharField(blank=True, max_length=64)),
                ('hectares', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('boundary_geojson', models.JSONField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='registry.party')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=48, unique=True)),
                ('label_key', models.CharField(max_length=32)),
                ('group_key', models.CharField(max_length=32)),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('org', 'Organisation'), ('facility', 'Facility'), ('region', 'Region'), ('national', 'National')], max_length=16)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('capabilities', models.ManyToManyField(related_name='roles', to='registry.capability')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season_year', models.PositiveSmallIntegerField()),
                ('planted_hectares', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_yield_g', models.BigIntegerField(default=0)),
                ('harvest_from', models.DateField(blank=True, null=True)),
                ('harvest_to', models.DateField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='registry.farm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='registry.product')),
            ],
            options={
                'ordering': ['-season_year', 'farm__code'],
                'constraints': [models.UniqueConstraint(fields=('farm', 'product', 'season_year'), name='uniq_plan_per_season')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility_codes', models.JSONField(blank=True, default=list)),
                ('is_primary', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='registry.party')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='registry.role')),
            ],
            options={
                'ordering': ['party__code', 'user__display_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'party', 'role'), name='uniq_membership')],
            },
        ),
        migrations.CreateModel(
            name='PartyVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('review', 'In review'), ('fail', 'Fail'), ('pending', 'Not started')], default='pending', max_length=8)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='registry.party')),
                ('verification_check', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='registry.verificationcheck')),
            ],
            options={
                'ordering': ['party__code', 'verification_check__sort_order'],
                'constraints': [models.UniqueConstraint(fields=('party', 'verification_check'), name='uniq_party_check')],
            },
        ),
    ]
