# Generated by Django 6.1 on 2026-08-27 07:16

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(choices=[('UZS', 'Uzbek sum'), ('USD', 'US dollar'), ('JPY', 'Japanese yen')], default='UZS', max_length=3)),
                ('fx_rate_to_uzs', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('excursion_code', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('approved', 'Approved'), ('paid', 'Paid'), ('declined', 'Declined')], default='draft', max_length=12)),
                ('filed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('decided_on', models.DateField(blank=True, null=True)),
                ('assessed_minor', models.BigIntegerField(default=0)),
                ('port_reference', models.CharField(blank=True, max_length=64)),
                ('port_state', models.CharField(blank=True, max_length=32)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-filed_on', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Encumbrance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(choices=[('UZS', 'Uzbek sum'), ('USD', 'US dollar'), ('JPY', 'Japanese yen')], default='UZS', max_length=3)),
                ('fx_rate_to_uzs', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('created_on', models.DateField(default=django.utils.timezone.localdate)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reference', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='FinanceApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(choices=[('UZS', 'Uzbek sum'), ('USD', 'US dollar'), ('JPY', 'Japanese yen')], default='UZS', max_length=3)),
                ('fx_rate_to_uzs', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('inventory', 'Inventory finance'), ('pre_export', 'Pre-export finance'), ('working', 'Working capital')], default='inventory', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('review', 'In review'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('repaid', 'Repaid'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('ltv_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('applied_on', models.DateField(default=django.utils.timezone.localdate)),
                ('decided_on', models.DateField(blank=True, null=True)),
                ('port_reference', models.CharField(blank=True, max_length=64)),
                ('port_state', models.CharField(blank=True, max_length=32)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-applied_on', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(choices=[('UZS', 'Uzbek sum'), ('USD', 'US dollar'), ('JPY', 'Japanese yen')], default='UZS', max_length=3)),
                ('fx_rate_to_uzs', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('storage', 'Storage cover'), ('cargo', 'Cargo cover')], default='storage', max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('covered_shipment_code', models.CharField(blank=True, max_length=32)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('deductible_minor', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'policies',
                'ordering': ['-starts_on', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SettlementAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(choices=[('UZS', 'Uzbek sum'), ('USD', 'US dollar'), ('JPY', 'Japanese yen')], default='UZS', max_length=3)),
                ('fx_rate_to_uzs', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('export_contract_code', models.CharField(db_index=True, max_length=32)),
                ('priority', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('lender', 'Loan repayment'), ('insurer', 'Premium'), ('logistics', 'Logistics'), ('operator', 'Operator fee'), ('farmer', 'Producer'), ('tax', 'Duties and tax')], max_length=12)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('released', 'Released'), ('paid', 'Paid')], default='planned', max_length=10)),
                ('paid_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['export_contract_code', 'priority'],
            },
        ),
    ]
