# Generated by Django 6.1 on 2026-08-27 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='lots.lot'),
        ),
    ]
