# Generated by Django 6.1 on 2026-08-27 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_initial'),
        ('lots', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encumbrance',
            name='holder_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liens_held', to='registry.party'),
        ),
        migrations.AddField(
            model_name='encumbrance',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encumbrances', to='lots.lot'),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='applicant_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_applications', to='registry.party'),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='collateral_lots',
            field=models.ManyToManyField(blank=True, related_name='finance_applications', to='lots.lot'),
        ),
        migrations.AddField(
            model_name='financeapplication',
            name='lender_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_underwritten', to='registry.party'),
        ),
        migrations.AddField(
            model_name='encumbrance',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encumbrances', to='finance.financeapplication'),
        ),
        migrations.AddField(
            model_name='policy',
            name='covered_lots',
            field=models.ManyToManyField(blank=True, related_name='policies', to='lots.lot'),
        ),
        migrations.AddField(
            model_name='policy',
            name='holder_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies_held', to='registry.party'),
        ),
        migrations.AddField(
            model_name='policy',
            name='insurer_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies_written', to='registry.party'),
        ),
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='finance.policy'),
        ),
        migrations.AddField(
            model_name='settlementallocation',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_lines', to='registry.party'),
        ),
        migrations.AddIndex(
            model_name='encumbrance',
            index=models.Index(fields=['lot', 'released_at'], name='finance_enc_lot_id_7359a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlementallocation',
            constraint=models.UniqueConstraint(fields=('export_contract_code', 'priority'), name='uniq_waterfall_priority'),
        ),
    ]
