# Generated by Django 6.1 on 2026-08-27 07:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionExcursion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('scope_type', models.CharField(choices=[('storage_zone', 'Storage zone'), ('shipment', 'Shipment')], max_length=16)),
                ('scope_code', models.CharField(max_length=32)),
                ('metric', models.CharField(choices=[('temp', 'Temperature'), ('rh', 'Humidity')], default='temp', max_length=8)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('peak_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=6)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=8)),
                ('sensor_id', models.CharField(blank=True, max_length=32)),
                ('trace', models.JSONField(blank=True, default=list)),
                ('affected_lot_codes', models.JSONField(blank=True, default=list)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ConditionReading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('storage_zone', 'Storage zone'), ('shipment', 'Shipment')], max_length=16)),
                ('scope_code', models.CharField(max_length=32)),
                ('sensor_id', models.CharField(max_length=32)),
                ('recorded_at', models.DateTimeField()),
                ('temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rh_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['scope_type', 'scope_code', '-recorded_at'], name='storage_con_scope_t_975a21_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope_type', 'scope_code', 'sensor_id', 'recorded_at'), name='uniq_reading_per_sensor_instant')],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('hub', 'Hub'), ('packhouse', 'Pack-house'), ('chamber', 'ZEROCO chamber'), ('yard', 'Yard')], default='hub', max_length=16)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('district', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('operator_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='registry.party')),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GateArrival',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.CharField(max_length=32)),
                ('expected_at', models.DateTimeField()),
                ('estimated_weight_g', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('weighing', 'On the weighbridge'), ('registered', 'Registered'), ('rejected', 'Turned away')], default='queued', max_length=12)),
                ('lot_code', models.CharField(blank=True, max_length=32)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='storage.facility')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='registry.farm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='registry.product')),
            ],
            options={
                'ordering': ['expected_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('mode', models.CharField(choices=[('zeroco', 'ZEROCO'), ('cold', 'Conventional cold'), ('pre', 'Pre-cool'), ('dry', 'Dry')], max_length=8)),
                ('capacity_g', models.BigIntegerField()),
                ('target_temp_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('target_rh_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tolerance_temp_c', models.DecimalField(decimal_places=2, default=2, max_digits=4)),
                ('tolerance_rh_pct', models.DecimalField(decimal_places=2, default=5, max_digits=4)),
                ('current_temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_rh_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reading_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='storage.facility')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StoragePlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(blank=True, max_length=16)),
                ('quantity_g', models.BigIntegerField()),
                ('placed_at', models.DateTimeField()),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='lots.lot')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='storage.storagezone')),
            ],
            options={
                'ordering': ['-placed_at'],
                'indexes': [models.Index(fields=['zone', 'removed_at'], name='storage_sto_zone_id_fc3572_idx')],
            },
        ),
    ]
