# Generated by Django 6.1 on 2026-08-27 07:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('subject_type', models.CharField(choices=[('lot', 'Lot'), ('shipment', 'Shipment'), ('party', 'Organisation'), ('export_contract', 'Export contract'), ('qc_record', 'QC record'), ('claim', 'Claim')], max_length=20)),
                ('subject_code', models.CharField(db_index=True, max_length=48)),
                ('doc_type', models.CharField(choices=[('phyto', 'Phytosanitary certificate'), ('origin', 'Certificate of origin'), ('invoice', 'Commercial invoice'), ('packing', 'Packing list'), ('lab', 'Laboratory report'), ('cmr', 'CMR consignment note'), ('lc', 'Letter of credit'), ('contract', 'Contract'), ('licence', 'Licence'), ('charter', 'Charter'), ('registration', 'Registration certificate'), ('other', 'Other')], max_length=16)),
                ('name_key', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Awaited'), ('issued', 'Issued'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('issued_by', models.CharField(blank=True, max_length=160)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('file_ref', models.CharField(blank=True, max_length=512)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['subject_code', 'doc_type'],
                'indexes': [models.Index(fields=['subject_type', 'subject_code'], name='documents_d_subject_b8b047_idx')],
            },
        ),
    ]
