# Generated by Django 6.1 on 2026-09-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='byte_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('phyto', 'Phytosanitary certificate'), ('origin', 'Certificate of origin'), ('invoice', 'Commercial invoice'), ('packing', 'Packing list'), ('lab', 'Laboratory report'), ('cmr', 'CMR consignment note'), ('lc', 'Letter of credit'), ('contract', 'Contract'), ('licence', 'Licence'), ('charter', 'Charter'), ('photo', 'Photograph'), ('registration', 'Registration certificate'), ('other', 'Other')], max_length=16),
        ),
    ]
